### ISSUE TITLE
ImportError: cannot import name 'QWebEngineDownloadItem' under Arch Linux

### ISSUE THREAD

**Issue by Xananax** [kovidgoyal/vise#2]
It seems the dependencies listed in `dependencies.txt` are not enough under Arch.

In order to be able to run Vise, I had to add `qt5-webengine`.

For anyone trying to build & run under Arch Linux, here are the steps:

```
sudo pacman -S qt5-base python-pyqt5 libsodium python-yaml python-apsw qt5-webengine --needed
cd dir_where_cloned_git
./build
python3 ./
```

I'm just posting this for other potential people curious to see what you've done, the issue is actually resolved.

Thanks!

**Comment by kovidgoyal** [comment]
I've added a note in dependencies.txt about needing webengine
