### ISSUE TITLE
Any future plans for a "public" release

### ISSUE THREAD

**Issue by bbtdev** [kovidgoyal/vise#5]
Hello,
 
I really enjoy kitty terminal so I checked your github repos and stumbled on this. I know you answered this before but more then a year passed and I was wondering if you see a possibility for a public release in the near future?

**Comment by kovidgoyal** [comment]
Sadly, I'm afraid kitty and calibre already take up all my available bandwidth -- I simply dont have the time/energy required to support something of the scope of vise for public consumption. I will continue to maintain it as I still use it myself, but that is about all.
