### ISSUE TITLE
Building on M1 Mac

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/vise#6]
Hi there! So I tried installing `vise` on MacOS. Here is my journey

1. mkvirtualenv vise
2. pip install --upgrade pip
3. pip install apsw
4. brew install qt@5
    a. Includes QtWebEngine afaia
5. pip install PyQt5
    a.  ran into a problem, looked it up on [StackOverflow](https://stackoverflow.com/a/71022563/4204961) ended up running `pip install pyqt5-sip`
    b. ran into [another problem](https://stackoverflow.com/a/73818706/4204961), after I solved it installing PyQt5 worked!
6. addeed `/opt/homebrew/opt/qt5/bin` to path
7. brew install libsodium
8. npm i -g rapydscript-ng
9. git clone https://github.com/kovidgoyal/vise
10. cd vise
11. rapydscript --js-version 6 --cache-dir ./.build-cache ./client/main.pyj > ./resources/vise-client.js
12. `python3 .`
    a. Said `Your system appears to be missing the qt-webengine package`
    b. Ran pip install -vv pyqtwebengine
    c. Still says `Your system appears to be missing the qt-webengine package` 😭

Here is `pip list`:

```
apsw          3.39.4.0
pip           22.3
PyQt5         5.15.7
PyQt5-sip     12.11.0
PyQtWebEngine 5.15.6
setuptools    62.5.0
wheel         0.37.1
```

I am on M1 MacOS 12.6, python3==3.8.12 (I can go higher, but this is the lowest version supported for M1)

**Comment by hacker-DOM** [comment]
Ah, it seems that PyQt6 is required. So I did:

13. pip install -vv pyqt6
14. pip install -vv pyqt6-webengine
15. pip install pyyaml

**Comment by hacker-DOM** [comment]
16. `ln -s /opt/homebrew/Cellar/libsodium/1.0.18_1/lib/libsodium.23.dylib libsodium.dylib` And it works!

**Comment by hacker-DOM** [comment]
Btw, do you pronounce in as Mike, or vis, or veeseh? And where does the name come from (I'm guessing vi is for visual)?

**Comment by kovidgoyal** [comment]
vi comes from the vi editor. vise is basically VIm + browSE. It is
pronounced as the English word vise https://www.merriam-webster.com/dictionary/vise
